#!/bin/bash
NAME=${PWD##*/}

docker run -d --rm --net host -v ~/:/notebooks -e VEHICLE_NAME="theducknight" -e ROS_IP="109.202.221.9" -e ROS_MASTER_URI="http://109.202.221.93:11311/" --name dt-jupyter-node duckietown/dt-$NAME:v1-amd64
